version: '3'

includes:
  contents:
    taskfile: 'https://github.com/attakei/workspace-configs.git//projects/sphinx-doc/Taskfile.yaml?tag=v0.6.0'
    flatten: true
    vars:
      RUN_PYTHON: 'uv run'
      SPHINX_ROOT_DIR: ''
      SPHINX_SOURCE_DIR: 'contents'
      SPHINX_OUTPUT_DIR: 'build'
      SPHINX_DEFAULT_BUILDER: 'dirrevealjs'

tasks:
  setup:
    desc: 'Setup workspace'
    cmds:
      - 'uv sync --frozen'
      - 'lefthook install'
  verify:
    desc: 'Verify environment by all procs'
    cmds:
      - 'lefthook run pre-commit --all-files'
      - task: 'build-linkcheck'
  setup-publish:
    desc: 'Setup workspace for publishing'
    cmds:
      - 'uv sync --frozen --group=publish'
      # NOTE: It will show warnings. Please install deps manually for your distribution.
      - 'uv run playwright install'
  build-publish:
    desc: 'Build contents for publishing'
    cmds:
      - task: 'build-dirrevealjs'
        vars:
          CLI_ARGS: '--tag screenshot'
      - task: 'build-dirhtml'
      - |
        {{if eq OS "windows"}}
          xcopy build\\dirhtml\\index.html build\\dirrevealjs\\ /Y
        {{else}}
          cp build/dirhtml/index.html build/dirrevealjs/index.html
        {{end}}
  devserver:
    desc: 'Run docs server'
    cmds:
      - task: 'dev'
        vars:
          CLI_ARGS: '--ignore "contents/_static/css" --tag talk'
  wrangler:
    desc: 'Run Cloudflare CLI'
    cmds:
      - 'bun x wrangler@4.34.0 {{.TASK_ARGS}} {{.CLI_ARGS}}'
  deploy:
    desc: 'Deploy contents to Cloudflare Workers'
    cmds:
      - task: 'setup-publish'
      - task: 'build-publish'
      - task: 'wrangler'
        vars:
          TASK_ARGS: 'deploy'
